# **PyTorch tutorial**
This is a basic tutorial for first time users of PyTorch with some code experience. It reviewes mathematical operations with tensors, how to solve linear equations, automatic differentiation and optimization techniques throught examples.



## Installing and loading PyTorch

In [1]:
!pip install torch


[notice] A new release of pip is available: 23.0.1 -> 23.3.1
[notice] To update, run: C:\Users\ddominguezvazquez\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [3]:
import torch

## Data types and definitions of tensors
- **torch.mm**: performs a matrix multiplication without broadcasting (2D tensor) by (2D tensor)
- **torch.mul**: performs a elementwise multiplication with broadcasting (Tensor) by (Tensor or Number)
- **torch.matmul**: matrix product with broadcasting (Tensor) by (Tensor) with different behaviors depending on the tensor shapes (dot product, matrix product, batched matrix products).

In [4]:
a1=torch.tensor([1.3])
print(a1)
print(a1.type())
print(a1.dtype)
print(a1.size())

tensor([1.3000])
torch.FloatTensor
torch.float32
torch.Size([1])


In [5]:
a12 = torch.tensor([1, 2])
print(a12)
print(a12.size())
a22 = torch.tensor([[2, 5],[3, 5]])
print(a22)
print(a22.size())
a23 = torch.tensor([[1, 2, 6],[10, 2, 8]])
print(a23)
print(a23.size())

tensor([1, 2])
torch.Size([2])
tensor([[2, 5],
        [3, 5]])
torch.Size([2, 2])
tensor([[ 1,  2,  6],
        [10,  2,  8]])
torch.Size([2, 3])


In [6]:
print(torch.matmul(a22,a23))

tensor([[52, 14, 52],
        [53, 16, 58]])


In [73]:
print(torch.mul(a22,a22))
print(torch.mul(a12*100,a22))
print(torch.matmul(a22,a22))

tensor([[ 4, 25],
        [ 9, 25]])
tensor([[ 200, 1000],
        [ 300, 1000]])
tensor([[19, 35],
        [21, 40]])


In [49]:
a23 = torch.tensor([[1, 2, 6],[10, 2, 8]])
print(a23)
print(a23.size())
a3timesa2 = torch.matmul(a3,a2)
print(a3timesa2)

tensor([[2, 4, 5],
        [3, 5, 5]])
torch.Size([2, 3])
tensor([[ 1,  2],
        [10,  2]])
torch.Size([2, 2])
tensor([[ 8, 14, 15],
        [26, 50, 60]])


In [ ]:
torch.ones([2, 4], dtype=torch.float64)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)